---
- hosts: ipsec

  handlers:
  - include: handlers.yml

  tasks: 

  - name: Install ipsec-tools
    become: yes
    apt: name=ipsec-tools
         state=present

  - name: Add flush command to ipsec-tools.conf
    become: yes
    lineinfile: dest=/etc/ipsec-tools.conf line="flush;" create=yes
    notify:
    - setkey restart

  - name: Add spdflush command to ipsec-tools.conf
    become: yes
    lineinfile: dest=/etc/ipsec-tools.conf line="spdflush;" create=yes
    notify:
    - setkey restart

  - name: Install ipsec-tools.d config files for each host in inventory
    become: yes
    template: src=templates/ipsec-tools-manual.conf dest=/etc/ipsec-tools.d/{{item}}.conf
    vars:
      to_host: "{{item}}"
    with_items:
    - "{{ groups['ipsec']|difference([ inventory_hostname ] ) }}"
    notify:
    - setkey restart

  - name: Enable setkey service
    become: yes
    service: name=setkey
             enabled=true
             state=started
