---
- hosts: ipsec

  handlers:
  - include: handlers.yml

  tasks:
  - name: Install ipsec-tools and racoon
    become: yes
    apt: name={{item}}
         state=present
    with_list:
      - ipsec-tools
      - racoon

  - name: Install ipsec-tools.conf
    become: yes
    template: src=templates/ipsec-tools.conf dest=/etc/ipsec-tools.conf
    notify:
    - setkey restart

  - name: install racoon.conf
    template: src=templates/racoon.conf dest=/etc/racoon/racoon.conf
    become: yes
    notify:
    - racoon reload

  - name: install psk.txt
    template: src=templates/psk.txt dest=/etc/racoon/psk.txt
    become: yes
    notify:
    - racoon reload

  - name: enable racoon service
    become: yes
    service: name=racoon
             state=started
             enabled=yes
